/**
 * Generate admin React component stubs based on uiNeeds.
 * Templates follow existing glass-panel/glass-card admin patterns.
 */
import type { SkillSpec } from '../feature-builder-spec-types'
import type { FileDescriptor } from './generate-types'

/** Convert kebab-case to PascalCase */
function pascal(name: string): string {
  return name.split('-').map(s => s.charAt(0).toUpperCase() + s.slice(1)).join('')
}

/** Generate field inputs JSX for form/editor */
function fieldInputs(spec: SkillSpec): string {
  return spec.dataSchema.suggestedFields.map(f => {
    if (f.type === 'boolean') {
      return `        <label style={{ fontSize: '0.82rem', display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
          <input type="checkbox" checked={form.${camelize(f.name)} || false} onChange={e => setForm(p => ({ ...p, ${camelize(f.name)}: e.target.checked }))} />
          ${f.name}
        </label>`
    }
    if (f.type === 'rich-text') {
      return `        <div>
          <label style={{ fontSize: '0.78rem', color: '#64748b' }}>${f.name}</label>
          <textarea style={inputStyle} rows={4} value={form.${camelize(f.name)} || ''} onChange={e => setForm(p => ({ ...p, ${camelize(f.name)}: e.target.value }))} />
        </div>`
    }
    const inputType = f.type === 'number' ? 'number' : f.type === 'date' ? 'date' : 'text'
    return `        <div>
          <label style={{ fontSize: '0.78rem', color: '#64748b' }}>${f.name}</label>
          <input style={inputStyle} type="${inputType}" value={form.${camelize(f.name)} || ''} onChange={e => setForm(p => ({ ...p, ${camelize(f.name)}: e.target.value }))} />
        </div>`
  }).join('\n')
}

/** Convert kebab-case to camelCase */
function camelize(s: string): string {
  return s.replace(/-([a-z])/g, (_, c) => c.toUpperCase())
}

function listTemplate(spec: SkillSpec): string {
  const pc = pascal(spec.skill.name)
  return `/**
 * ${spec.skill.name} list — displays all entries with actions.
 * Generated by Feature Builder. Customize as needed.
 */
import { useState, useEffect } from 'react'
import { useLocation } from 'wouter'
import { api } from '@/lib/admin/api-client'

export function Feature${pc}List() {
  const [, navigate] = useLocation()
  const [entries, setEntries] = useState<any[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    api.collections.list('${spec.skill.name}').then(res => {
      if (res.ok && res.data) setEntries((res.data as any).entries || [])
      setLoading(false)
    })
  }, [])

  if (loading) return <div className="glass-panel" style={{ padding: '2rem', textAlign: 'center' }}>Loading…</div>

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
        <h1 style={{ fontSize: '1.1rem', fontWeight: 700, color: '#1e293b', margin: 0 }}>${spec.treeidIntegration.navItem.label}</h1>
        <button className="admin-btn admin-btn-primary" onClick={() => navigate('/${spec.skill.name}/new')}>+ New</button>
      </div>
      {entries.length === 0
        ? <div className="glass-panel" style={{ padding: '2rem', textAlign: 'center', color: '#94a3b8' }}>No entries yet.</div>
        : <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
            {entries.map((e: any) => (
              <div key={e.slug} className="glass-card" style={{ padding: '0.75rem 1rem', borderRadius: '10px', cursor: 'pointer', display: 'flex', justifyContent: 'space-between' }} onClick={() => navigate(\`/${spec.skill.name}/\${e.slug}\`)}>
                <span style={{ fontWeight: 600, fontSize: '0.85rem' }}>{e.title || e.slug}</span>
                <span style={{ fontSize: '0.75rem', color: '#94a3b8' }}>{e.status || ''}</span>
              </div>
            ))}
          </div>
      }
    </div>
  )
}
`
}

function editorTemplate(spec: SkillSpec): string {
  const pc = pascal(spec.skill.name)
  const fields = spec.dataSchema.suggestedFields
  const defaultForm = fields.map(f => `${camelize(f.name)}: ''`).join(', ')
  return `/**
 * ${spec.skill.name} editor — create/edit a single entry.
 * Generated by Feature Builder. Customize as needed.
 */
import { useState, useEffect } from 'react'
import { useLocation, useRoute } from 'wouter'
import { api } from '@/lib/admin/api-client'

const inputStyle = { width: '100%', padding: '6px 10px', borderRadius: '6px', border: '1px solid #e2e8f0', fontSize: '0.82rem', boxSizing: 'border-box' as const }

export function Feature${pc}Editor() {
  const [, navigate] = useLocation()
  const [, params] = useRoute('/${spec.skill.name}/:slug')
  const slug = params?.slug
  const isNew = slug === 'new'
  const [form, setForm] = useState<Record<string, any>>({ ${defaultForm} })
  const [saving, setSaving] = useState(false)

  useEffect(() => {
    if (!isNew && slug) {
      api.collections.read('${spec.skill.name}', slug).then(res => {
        if (res.ok && res.data) setForm(res.data as any)
      })
    }
  }, [slug])

  async function handleSave() {
    setSaving(true)
    if (isNew) {
      const res = await api.collections.create('${spec.skill.name}', form)
      if (res.ok) navigate('/${spec.skill.name}')
    } else if (slug) {
      await api.collections.update('${spec.skill.name}', slug, form)
    }
    setSaving(false)
  }

  return (
    <div style={{ maxWidth: '600px' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', marginBottom: '1.5rem' }}>
        <button className="admin-btn" onClick={() => navigate('/${spec.skill.name}')}>← Back</button>
        <h1 style={{ fontSize: '1.1rem', fontWeight: 700, color: '#1e293b', margin: 0 }}>{isNew ? 'New' : 'Edit'} ${spec.treeidIntegration.navItem.label}</h1>
      </div>
      <div className="glass-panel" style={{ padding: '1.5rem', borderRadius: '14px' }}>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem', marginBottom: '1.5rem' }}>
${fieldInputs(spec)}
        </div>
        <button className="admin-btn admin-btn-primary" onClick={handleSave} disabled={saving} style={{ width: '100%' }}>
          {saving ? 'Saving…' : 'Save'}
        </button>
      </div>
    </div>
  )
}
`
}

function formTemplate(spec: SkillSpec): string {
  // Generate form directly instead of regex-replacing editor template
  // to avoid corrupting names containing "editor"
  const pc = pascal(spec.skill.name)
  const fields = spec.dataSchema.suggestedFields
  const defaultForm = fields.map(f => `${camelize(f.name)}: ''`).join(', ')
  return `/**
 * ${spec.skill.name} form — create/edit a single entry.
 * Generated by Feature Builder. Customize as needed.
 */
import { useState, useEffect } from 'react'
import { useLocation, useRoute } from 'wouter'
import { api } from '@/lib/admin/api-client'

const inputStyle = { width: '100%', padding: '6px 10px', borderRadius: '6px', border: '1px solid #e2e8f0', fontSize: '0.82rem', boxSizing: 'border-box' as const }

export function Feature${pc}Form() {
  const [, navigate] = useLocation()
  const [, params] = useRoute('/${spec.skill.name}/:slug')
  const slug = params?.slug
  const isNew = slug === 'new'
  const [form, setForm] = useState<Record<string, any>>({ ${defaultForm} })
  const [saving, setSaving] = useState(false)

  useEffect(() => {
    if (!isNew && slug) {
      api.collections.read('${spec.skill.name}', slug).then(res => {
        if (res.ok && res.data) setForm(res.data as any)
      })
    }
  }, [slug])

  async function handleSave() {
    setSaving(true)
    if (isNew) {
      const res = await api.collections.create('${spec.skill.name}', form)
      if (res.ok) navigate('/${spec.skill.name}')
    } else if (slug) {
      await api.collections.update('${spec.skill.name}', slug, form)
    }
    setSaving(false)
  }

  return (
    <div style={{ maxWidth: '600px' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', marginBottom: '1.5rem' }}>
        <button className="admin-btn" onClick={() => navigate('/${spec.skill.name}')}>← Back</button>
        <h1 style={{ fontSize: '1.1rem', fontWeight: 700, color: '#1e293b', margin: 0 }}>{isNew ? 'New' : 'Edit'} ${spec.treeidIntegration.navItem.label}</h1>
      </div>
      <div className="glass-panel" style={{ padding: '1.5rem', borderRadius: '14px' }}>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem', marginBottom: '1.5rem' }}>
${fieldInputs(spec)}
        </div>
        <button className="admin-btn admin-btn-primary" onClick={handleSave} disabled={saving} style={{ width: '100%' }}>
          {saving ? 'Saving…' : 'Save'}
        </button>
      </div>
    </div>
  )
}
`
}

function dashboardTemplate(spec: SkillSpec): string {
  const pc = pascal(spec.skill.name)
  return `/** ${spec.skill.name} dashboard — Generated by Feature Builder. */
import { useState, useEffect } from 'react'
import { api } from '@/lib/admin/api-client'

export function Feature${pc}Dashboard() {
  const [count, setCount] = useState(0)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    api.collections.list('${spec.skill.name}').then(res => {
      if (res.ok && res.data) setCount((res.data as any).total || 0)
      setLoading(false)
    })
  }, [])

  if (loading) return <div className="glass-panel" style={{ padding: '2rem', textAlign: 'center' }}>Loading…</div>

  return (
    <div>
      <h1 style={{ fontSize: '1.1rem', fontWeight: 700, color: '#1e293b', marginBottom: '1rem' }}>${spec.treeidIntegration.navItem.label}</h1>
      <div className="glass-card" style={{ padding: '1.5rem', borderRadius: '10px', textAlign: 'center' }}>
        <div style={{ fontSize: '2rem', fontWeight: 700, color: '#3b82f6' }}>{count}</div>
        <div style={{ fontSize: '0.8rem', color: '#64748b' }}>Total entries</div>
      </div>
    </div>
  )
}
`
}

export function generateAdminComponents(spec: SkillSpec): FileDescriptor[] {
  const base = `src/components/admin/${spec.skill.name}`
  const ui = spec.treeidIntegration.uiNeeds

  if (ui === 'none') return []
  if (ui === 'dashboard') {
    return [{ path: `${base}/feature-${spec.skill.name}-dashboard.tsx`, content: dashboardTemplate(spec) }]
  }
  if (ui === 'form') {
    return [{ path: `${base}/feature-${spec.skill.name}-form.tsx`, content: formTemplate(spec) }]
  }
  // list-detail (default)
  return [
    { path: `${base}/feature-${spec.skill.name}-list.tsx`, content: listTemplate(spec) },
    { path: `${base}/feature-${spec.skill.name}-editor.tsx`, content: editorTemplate(spec) },
  ]
}
