/**
 * Generate an Astro API route with CRUD for the feature's content.
 * Follows existing patterns: prerender=false, feature guard, json helper.
 */
import type { SkillSpec } from '../feature-builder-spec-types'
import type { FileDescriptor } from './generate-types'

export function generateApiRoute(spec: SkillSpec): FileDescriptor[] {
  const name = spec.skill.name
  const label = spec.treeidIntegration.navItem.label

  const content = `/**
 * CRUD API for ${label} — auto-generated by Feature Builder.
 * Reads/writes YAML files in src/content/${name}/.
 */
import type { APIRoute } from 'astro'
import { checkFeatureEnabled } from '@/lib/admin/feature-guard'
import fs from 'node:fs/promises'
import path from 'node:path'
import yaml from 'js-yaml'

export const prerender = false

function json(data: unknown, status = 200): Response {
  return new Response(JSON.stringify(data), {
    status,
    headers: { 'Content-Type': 'application/json' },
  })
}

const CONTENT_DIR = path.join(process.cwd(), 'src/content/${name}')

async function ensureDir() {
  await fs.mkdir(CONTENT_DIR, { recursive: true })
}

/** Sanitize slug to prevent path traversal */
function safeSlug(raw: string | null): string | null {
  if (!raw) return null
  const cleaned = raw.replace(/[^a-z0-9-]/g, '')
  return cleaned || null
}

export const GET: APIRoute = async ({ url }) => {
  const fc = checkFeatureEnabled('${name}')
  if (!fc.enabled) return fc.response

  const slug = safeSlug(url.searchParams.get('slug'))
  await ensureDir()

  if (slug) {
    try {
      const raw = await fs.readFile(path.join(CONTENT_DIR, slug + '.yaml'), 'utf-8')
      const data = yaml.load(raw) as Record<string, unknown>
      return json({ ok: true, data: { ...data, slug } })
    } catch {
      return json({ ok: false, error: 'Not found' }, 404)
    }
  }

  // List all entries
  try {
    const files = (await fs.readdir(CONTENT_DIR)).filter(f => f.endsWith('.yaml'))
    const entries = await Promise.all(
      files.map(async (f) => {
        const raw = await fs.readFile(path.join(CONTENT_DIR, f), 'utf-8')
        const data = yaml.load(raw) as Record<string, unknown>
        return { ...data, slug: f.replace('.yaml', '') }
      }),
    )
    return json({ ok: true, data: { entries, total: entries.length } })
  } catch {
    return json({ ok: true, data: { entries: [], total: 0 } })
  }
}

export const POST: APIRoute = async ({ request }) => {
  const fc = checkFeatureEnabled('${name}')
  if (!fc.enabled) return fc.response

  const body = await request.json()
  const slug = body.slug || body.title?.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') || Date.now().toString()
  await ensureDir()

  const { slug: _, ...data } = body
  await fs.writeFile(path.join(CONTENT_DIR, slug + '.yaml'), yaml.dump(data), 'utf-8')
  return json({ ok: true, data: { slug } })
}

export const PUT: APIRoute = async ({ url, request }) => {
  const fc = checkFeatureEnabled('${name}')
  if (!fc.enabled) return fc.response

  const slug = safeSlug(url.searchParams.get('slug'))
  if (!slug) return json({ ok: false, error: 'Missing slug' }, 400)

  const body = await request.json()
  const { slug: _, ...data } = body
  await ensureDir()
  await fs.writeFile(path.join(CONTENT_DIR, slug + '.yaml'), yaml.dump(data), 'utf-8')
  return json({ ok: true })
}

export const DELETE: APIRoute = async ({ url }) => {
  const fc = checkFeatureEnabled('${name}')
  if (!fc.enabled) return fc.response

  const slug = safeSlug(url.searchParams.get('slug'))
  if (!slug) return json({ ok: false, error: 'Missing slug' }, 400)

  try {
    await fs.unlink(path.join(CONTENT_DIR, slug + '.yaml'))
    return json({ ok: true })
  } catch {
    return json({ ok: false, error: 'Not found' }, 404)
  }
}
`

  return [{ path: `src/pages/api/admin/${name}.ts`, content }]
}
